version: '3.8'
services:
  nestexpense:
    image: postgres:14
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PWD}'
      POSTGRES_DB: '${DB_NAME}'

  test-db:
    image: postgres:14
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PWD}'
      POSTGRES_DB: '${DB_NAME}'
